---
version: '3.8'
services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        OS_VERSION: 12
        VERSION: 0.0.1
      labels:
        APPLICATION: POS_Admin
        # other labels to add later
    image: kevharv/pos-admin:latest
    container_name: POS_Admin
    env_file:
      - .env.development
      - .env.local
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    restart: on-failiure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s