# Add environment variables for everything
# Generate passwords and place in environment
# Create production variation
---
version: "3"
services:
  node:
    build: 
      context: ../node
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=18.12.0
    image: kevharv/pos-node
    container_name: node
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ../node:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_DB: pos
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres
    command: yarn dev

  postgres:
    image: postgres:12.3-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: